"""phase three jobs outbox integration tokens"""
from alembic import op
import sqlalchemy as sa


revision = '9254229814cf'
down_revision = 'bddda9993306'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'user_id'], ['memberships.workspace_id', 'memberships.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('owner_role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('generation', sa.Integer(), server_default='1', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('run_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('claim_token', sa.Uuid(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('result_key', sa.String(length=80), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','succeeded','failed','expired')", name='ck_job_status'),
    sa.CheckConstraint('attempts >= 0 AND run_attempts BETWEEN 0 AND 3 AND generation > 0', name='ck_job_budget'),
    sa.ForeignKeyConstraint(['workspace_id', 'owner_id'], ['memberships.workspace_id', 'memberships.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_status_lease', 'jobs', ['status', 'lease_until'], unique=False)
    op.create_index('ix_job_workspace_owner_created', 'jobs', ['workspace_id', 'owner_id', 'created_at'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_event_created', 'job_events', ['job_id', 'created_at'], unique=False)
    op.create_table('outbox_events',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('run_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claim_token', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('pending','dispatching','sent','exhausted')", name='ck_outbox_status'),
    sa.CheckConstraint('attempts >= 0 AND run_attempts BETWEEN 0 AND 5', name='ck_outbox_budget'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_outbox_due', 'outbox_events', ['status', 'next_attempt_at'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_due', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_job_event_created', table_name='job_events')
    op.drop_table('job_events')
    op.drop_index('ix_job_workspace_owner_created', table_name='jobs')
    op.drop_index('ix_job_status_lease', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('integration_tokens')
    # ### end Alembic commands ###
