"""persist execution retry backoff"""
from alembic import op
import sqlalchemy as sa


revision = '9d85bcfd0217'
down_revision = '9254229814cf'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ready_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ready_at')
    # ### end Alembic commands ###
